config/routes.rb
Backgroundsbybroccolini::Application.routes.draw do
  get "dashboard/index"

  root :to => "dashboard#index"

  match "tags"       => "tags#index"
  match "tags/:slug" => "tags#show", :as => :tag

  resources :brands,      :except => [:show]
  resources :backgrounds, :except => [:show]

  match "/brands/:slug"             => "brands#show",      :as => :brand
  match "/backgrounds/:slug"        => "backgrounds#show", :as => :background

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout"                 => "sessions#destroy", :as => :signout
end

app/models/background.rb
class Background < ActiveRecord::Base
  has_and_belongs_to_many :tags
  belongs_to :brand

  validates :name,  :presence => true, :uniqueness => true
  validates :brand, :presence => true
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :backgrounds, :dependent => :destroy

  validates :name, :presence => true, :uniqueness => true
  validates :url,  :presence => { :with => /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ix }
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :backgrounds
  validates :name, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid      = auth["uid"]
      user.name     = auth["user_info"]["name"]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user
  helper_method :sluggify

  private

  def require_login
    unless current_user
      redirect_to root_url
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def sluggify(string)
    string.downcase.gsub(/ |_/, "-")
  end
end

app/controllers/backgrounds_controller.rb
class BackgroundsController < ApplicationController
  before_filter :require_login, :except => [:index, :show]

  def index
    @backgrounds = Background.all
  end

  def show
    @background = Background.where(:slug => params[:slug]).first
  end

  def new
    @background = Background.new
  end

  def edit
    @background = Background.find(params[:id])
  end

  def create
    tags = params[:background].delete(:tags)
    @background = Background.new(params[:background])

    if @background.slug.blank?
      @background.slug = sluggify(@background.name)
    end

    update_tags(@background, tags)

    if @background.save
      redirect_to(background_path(@background.slug), :notice => 'Background was successfully created.')
    else
      render :action => "new"
    end
  end

  def update
    tags = params[:background].delete(:tags)
    @background = Background.find(params[:id])
    params[:background][:slug] = sluggify(params[:background][:slug])
    update_tags(@background, tags)

    if @background.update_attributes(params[:background])
      redirect_to(background_path(@background.slug), :notice => 'Background was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @background = Background.find(params[:id])
    @background.destroy
    redirect_to backgrounds_path
  end

  private

  def update_tags(background, tags)
    background.tags = []

    unless tags.blank?
      tags.split(",").each do |tag|
        background.tags << Tag.find_or_create_by_name(tag.strip.downcase)
      end
    end
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_filter :require_login, :except => [:index, :show]

  def index
    @brands = Brand.all
  end

  def show
    @brand = Brand.where(:slug => params[:slug]).first
  end

  def new
    @brand = Brand.new
  end

  def edit
    @brand = Brand.find(params[:id])
  end

  def create
    @brand = Brand.new(params[:brand])

    if @brand.slug.blank?
      @brand.slug = sluggify(@brand.name)
    end

    if @brand.save
      redirect_to(brand_path(@brand.slug), :notice => 'Brand was successfully created.')
    else
      render :action => "new"
    end
  end

  def update
    @brand = Brand.find(params[:id])
    @brand.slug = sluggify(@brand.slug)

    if @brand.update_attributes(params[:brand])
      redirect_to(brand_path(@brand.slug), :notice => 'Brand was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy
    redirect_to brands_path
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth  = request.env["omniauth.auth"]
    login = request.env["omniauth.auth"]["extra"]["user_hash"]["login"]

    if %w(broccolini veganstraightedge).include?(login)
      user = User.find_by_provider_and_uid(auth["provider"], auth["uid"].to_s) || User.create_with_omniauth(auth)
      session[:user_id] = user.id
    end
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.where(:name => params[:slug].gsub(/-/, " ")).first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_download(background)
    brand_slug      = sluggify(background.brand.name)
    background_slug = sluggify(background.name)
    url   = "https://github.com/broccolini/background_downloads/raw/master/downloads/#{brand_slug}/#{background_slug}.png"
    link_to "Download", url
  end
end

app/helpers/backgrounds_helper.rb
module BackgroundsHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/backgrounds/_background.html.erb
<div class="page">
<p id="notice"><%= notice %></p>

<dl>
  <dt>Name</dt>
  <dd><%= link_to_unless_current background.name, background_path(background.slug) %></dd>

  <dt>Download</dt>
  <dd><%= link_to_download(background) %></dd>

  <dt>Description</dt>
  <dd><%= background.description %></dd>

  <dt>Tags</dt>
  <dd>
    <ul>
      <% background.tags.each do |tag| %>
        <li><%= link_to tag.name, tag_path(sluggify(tag.name)) %></li>
      <% end %>
    </ul>
  </dd>

  <% if current_user %>
    <dt>Slug</dt>
    <dd><%= background.slug %></dd>
  <% end %>
</dl>

<% if current_user %>
  <%= link_to 'Edit', edit_background_path(background) %>
  <%= link_to 'Destroy', background, :confirm => 'Are you sure?', :method => :delete %>
<% end %>
</div>

app/views/backgrounds/_form.html.erb
<%= form_for(@background) do |f| %>
  <% if @background.errors.any? %>
    <div id="error_explanation" class="page">
      <h2><%= pluralize(@background.errors.count, "error") %> prohibited this background from being saved:</h2>

      <ul>
      <% @background.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :slug %><br />
    <%= f.text_field :slug %>
  </div>

  <div>
    <%= f.label :brand_id, "Brand" %>
    <%= f.select :brand_id, Brand.all.map { |b| [b.name, b.id] }, :include_blank => true %>
  </div>

  <div class="field">
    <%= f.label :tags %><br />
    <%= f.text_field :tags, :value => @background.tags.map{ |t| t.name }.join(", ") %>
  </div>

  <div class="actions">
    <%= f.submit "Submit", :disable_with => 'Submiting...' %>
  </div>
<% end %>

app/views/backgrounds/edit.html.erb
<div class="form">
<h1>Editing background</h1>

<%= render 'form' %>

<%= link_to 'Show', background_path(@background.slug) %>
</div>

app/views/backgrounds/index.html.erb
<div class="page">
<h1>Backgrounds</h1>

<ul>
  <% @backgrounds.each do |background| %>
    <li><%= render :partial => background %></li>
  <% end %>
</ul>
</div>

app/views/backgrounds/new.html.erb
<div class="page">
<h1>New background</h1>

<%= render 'form' %>
</div>

app/views/backgrounds/show.html.erb
<div class="detail">
	<div class="detail-img">
		<img src="/img/octotron-detail.png">	
	</div><!--backgrounds-img-->
	
	<div class="detail-content">
		<div class="info">
		<h2>OctoTron</h2>
		<p class="description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent non lorem et nunc tincid unt euismod. Praesent sed nunc vitae justo commodo posuere.</p>
		
		<div id="meta">
			<dl>
				<dt>Brand:</dt><dd>GitHub</dd>
			</dl>
			<dl>
				<dt>Movie:</dt><dd>Tron</dd>
			</dl>
			<dl>
				<dt>Tags:</dt><dd><a href="#">intense</a>, <a href="#">bright</a>, <a href="#">awesome</a></dd>
			</dl>
			<dl class="variations">
				<dt>Variations:</dt><dd><a href="#">OctoTron - dark blue</a></dd>
			</dl>
			</div><!--meta-->	
		</div><!--info-->
	</div><!--detail-content-->

	<div class="downloads">
		<h3>Download this background</h3><span class="download-desc">(Desktop, iPad, and iPhone)</span>
		
	</div><!--downloads-->
	
</div><!--detail-->

app/views/brands/_brand.html.erb
<p id="notice"><%= notice %></p>

<dl>
  <dt>Name</dt>
  <dd><%= link_to_unless_current brand.name, brand_path(brand.slug) %></dd>

  <dt>URL</dt>
  <dd><%= link_to brand.url, brand.url, :rel => "external" %></dd>
  
  <% if current_user %>
    <dt>Slug</dt>
    <dd><%= brand.slug %></dd>
  <% end %>
  
  <dt>Backgrounds</dt>
  <dd>
    <ul>
      <% brand.backgrounds.each do |background| %>
        <li><%= link_to background.name, background_path(background.slug) %></li>
      <% end %>
    </ul>
  </dd>
</dl>

<% if current_user %>
  <%= link_to 'Edit', edit_brand_path(brand) %>
  <%= link_to 'Destroy', brand, :confirm => 'Are you sure?', :method => :delete %>
<% end %>

app/views/brands/_form.html.erb
<%= form_for(@brand) do |f| %>
  <% if @brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% @brand.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :slug %><br />
    <%= f.text_field :slug %>
  </div>

  <div class="actions">
    <%= f.submit "Submit", :disable_with => 'Submiting...' %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing brand</h1>

<%= render 'form' %>

<%= link_to 'Show', brand_path(@brand.slug) %>

app/views/brands/index.html.erb
<h1>Brands</h1>

<ul>
  <% @brands.each do |brand| %>
    <li><%= render :partial => brand %></li>
  <% end %>
</ul>

app/views/brands/new.html.erb
<h1>New brand</h1>

<%= render 'form' %>

app/views/brands/show.html.erb
<%= render :partial => @brand %>

app/views/dashboard/index.html.erb
<div class="home">
	
	<div id="feature">
		<div class="feature-img">
		<img src="img/octotron.png">
		<div class="title">
		<h2>OctoTron</h2>
		</div><!--title-->
		</div><!--feature-img-->			
	<p class="description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent non lorem et nunc tincidunt euismod. Praesent sed nunc vitae justo commodo posuere.</p>
	<div id="meta">
		<dl>
			<dt>Brand:</dt><dd>GitHub</dd>
		</dl>
		<dl>
			<dt>Movie:</dt><dd>Tron</dd>
		</dl>
		<dl>
			<dt>Tags:</dt><dd><a href="#">intense</a>, <a href="#">bright</a>, <a href="#">awesome</a></dd>
		</dl>
		<dl class="variations">
			<dt>Variations:</dt><dd><a href="#">OctoTron - dark blue</a></dd>
		</dl>
		</div><!--meta-->			
	</div><!--feature-->
	
	<div class="grid">
		<ul class="backgrounds">
		<li><img src="img/octotron-2.png"><h3><a href="#">Another background</a></h3></li>
				<li><img src="img/octotron-2.png"><h3><a href="#">Another background</a></h3></li>
				<li><img src="img/octotron-2.png"><h3><a href="#">Another background</a></h3></li>
				<li><img src="img/octotron-2.png"><h3><a href="#">Another background</a></h3></li>
				<li><img src="img/octotron-2.png"><h3><a href="#">Another background</a></h3></li>
				<li><img src="img/octotron-2.png"><h3><a href="#">Another background</a></h3></li>
				
		</ul>
		</div><!--grid-->

	
	
	</div><!--home-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Backgrounds by broccolini</title>
  <%= stylesheet_link_tag "style" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
	<script type="text/javascript" src="http://use.typekit.com/ujg3ali.js"></script>
	<script type="text/javascript">try{Typekit.load();}catch(e){}</script>
</head>
<body>
	<div id="nav">
	<h1>Backgrounds <span class="designer">by broccolini</span></h1>
	<p>Wallpaper for desktops and devices.</p>


  <ul class="nav-list">
    <li><%= link_to_unless_current "Tags",        tags_path %></li>
    <li><%= link_to_unless_current "Brands",      brands_path %></li>
    <li><%= link_to_unless_current "Backgrounds", backgrounds_path %></li>

    <% if current_user %>
      <li><%= link_to_unless_current "New Brand", new_brand_path %></li>
      <li><%= link_to_unless_current "New Background", new_background_path %></li>
      <li><%= link_to "Sign Out", signout_path %></li>
    <% end %>
  </ul>
	</div><!--nav-list-->
</div><!--container-->

<div class="page">
  <%= yield %>
</div><!--page-->

  <footer>
    <% if Rails.env.development? && !current_user %>
      <%= link_to "Sign In with GitHub", "/auth/github" %>
    <% end %>
  </footer>
</body>
</html>

app/views/tags/_tag.html.erb
<h2>
  <%= link_to_unless_current tag.name, tag_path(sluggify(tag.name)) %>
</h2>

<ul>
  <% tag.backgrounds.each do |background| %>
    <li>
      <%= link_to background.name, background_path(background.slug) %>
    </li>
  <% end %>
</ul>

app/views/tags/index.html.erb
<h1>Tags</h1>

<ul>
  <% @tags.sort_by{ |t| t.name }.each do |tag| %>
    <li><%= render :partial => tag %></li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<%= render :partial => @tag %>